# Main header
dataset: 
    pointwise_data: example_pairwise_task/sample_dataset.jsonl
    id_key: id # key containing unique id
    text_key: text # key containing text
    min_comparisons: 20 # minimum number of comparisons to be made
    dataset_name: sample-pairwise-data

exemplars:
    use_exemplars: False
    path: sample_exemplars.jsonl
    num_exemplars: 2
    shuffle: True
    seed: 42

prompt_details: 
    path: example_pairwise_task/pairwise_prompt
    prompt_name: None
    output_var: response
    labels:  # keep this empty for open labels
    input_vars: [text1, text2]
    input_type: md

model_details:
    model_name: meta-llama/Llama-3.1-8B-Instruct
    model_family: llama
    scores: False
    batch_size: 8
    max_new_tokens: 10
    temperature: 0.01
        
output:
    output_dir: example_pairwise_task/output
    output_file: pairwise_results.jsonl
    output_bt_file: pairwise_results_bt.jsonl
    task_name: simple-qa