# FILEPATH: /fs/clip-political/rupak/hf-fewshot/configs/example_config.yaml

# Main header
exemplars:
    path: /fs/clip-political/rupak/hf-fewshot/example_task/sample_exemplars.jsonl
    num_exemplars: 2
    shuffle: False

prompts: 
    path: /fs/clip-political/rupak/hf-fewshot/example_task/sample_prompt.json
    prompt_name: question_answering_prompt
    output_var: answer
    labels:  # keep this empty for open labels
    input_vars: [question]
    
model_details:
    model_name: gpt-4-turbo
    model_family: gpt
    scores: False
    batch_size: 8
    max_new_tokens: 10
    temperature: 0.01
    
# The dataset should be a jsonlines file with keys that are of the following type 
dataset:
    # the unique_id of each example
    dataset_name: test-qa-dataset
    id_key: q_id
    path: /fs/clip-political/rupak/hf-fewshot/example_task/sample_dataset.jsonl
    
output:
    output_dir: /fs/clip-political/rupak/hf-fewshot/outputs
    output_file: sample_output.jsonl
    task_name: simple-qa