# FILEPATH: /fs/clip-political/rupak/hf-fewshot/configs/config_mistral_fewshot.yaml

# Main header
exemplars:
    path: exemplar_filepath.jsonl  # path to the exemplar file
    num_exemplars: 5
    shuffle_exemplars: False 

prompts: 
    path: /path/to/prompts.json 
    prompt_name: stance_detection # should correspond to a key in the prompts json dict 
    output_var: stance
    labels: [favor, against, neutral] # keep this empty for open labels
    input_vars: [text, topic]
    
model_details:
    model_name: mistralai/Mistral-7B-Instruct-v0.2
    model_family: mistral
    scores: False
    batch_size: 16
    max_new_tokens: 256
    temperature: 0.01
    
# The dataset should be a jsonlines file with keys that are of the following type 
dataset:
    # the unique_id of each example
    dataset_name: fda-decomps
    id_key: id
    path: /path/to/dataset.jsonl
    
output:
    output_dir: /path/to/output_dir
    task_name: fewshot-stance
