# FILEPATH: hf_fewshot/configs/example_qna_config.yaml

# Main header
exemplars:
    use_exemplars: True
    path: ../example_tasks/question_answering/exemplars.jsonl
    num_exemplars: 2
    shuffle: True
    seed: 42

prompt_details: 
    path: ../example_tasks/question_answering/zero_shot
    input_type: md
    prompt_name: question_answering_prompt
    output_var: answer
    labels:  # keep this empty for open labels
    input_vars: [question]
    
model_details:
    model_name: gpt-3.5-turbo
    model_family: gpt
    scores: False
    batch_size: 8
    max_new_tokens: 10
    temperature: 0.01
    
# The dataset should be a jsonlines file with keys that are of the following type 
dataset:
    # the unique_id of each example
    dataset_name: test-qa-dataset
    id_key: q_id
    path: ../example_tasks/question_answering/dataset.jsonl
    
output:
    output_dir: ../outputs
    output_file: sample_qna_output.jsonl
    task_name: simple-qa